[book]
authors = ["Scott Turner"]
title = "STEM Outreach Activities"
language = "en"
multilingual = false
src = "content"

[output.html]
mathjax-support = true

[output.html.print]
enable = false
git-repository-url = "https://github.com/cccu-uk/STEM_book/tree/main/content"
edit-url-template = "https://github.com/cccu-uk/STEM_book/edit/main/{path}"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2